%% Copyright (C) 2003 Mark Spink
%% 
%% This program is free software; you can redistribute it and/or modify
%% it under the terms of the GNU General Public License as published by
%% the Free Software Foundation; either version 2 of the License, or
%% (at your option) any later version.
%% 
%% This program is distributed in the hope that it will be useful,
%% but WITHOUT ANY WARRANTY; without even the implied warranty of
%% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
%% GNU General Public License for more details.
%% 
%% You should have received a copy of the GNU General Public License
%% along with this program; if not, see <http://www.gnu.org/licenses/>.

function nrbdemo()

lst = {'3D Line', 'demoline', 'Rectangle','demorect', ...
       'Circle and Arc','democirc','Helix','demohelix', ...
       'Ellipse', 'demoellip', ...
       'Test Curve','democurve', ...
       'Test Surface','demosurf', ...
       'Bilinear Surface','demo4surf', ...
       'Knot Insertion','demokntins', ...
       'Degree Elevation','demodegelev', ...
       'Curve derivatives','demodercrv', ...
       'Surface derivatives','demodersrf' ...
       'Cylinderical arc','democylind', ...
       'Ruled Surface','demoruled', ...
       'Coons Surface','democoons', ...
       'Test Extrusion','demoextrude', ...
       'Test Revolution - Cup','demorevolve', ...
       'Test Revolution - Ball & Torus','demotorus', ...
       '2D Geomtery','demogeom'};

for ii=1:2:length(lst)
  printf("Demo number %d: %s\n", (ii+1)/2, lst{ii})
  eval(lst{ii+1})
  pause
endfor
